[project]
name = "desiqso"
version = "0.1.4"
description = ""
authors = [
    {name = "Vincent Lefloch",email = "vincent.lefloch.vl@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "sparclclient (>=1.2.8,<2.0.0)",
    "tqdm (>=0.0.1,<0.0.2)",
    "astropy (>=7.2.0,<8.0.0)",
    "specutils (>=2.3.0,<3.0.0)",
    "matplotlib (>=3.10.8,<4.0.0)",
    "pandas (>=3.0.1,<4.0.0)",
    "voigtfit (>=3.22,<4.0)"
]

[tool.poetry]
packages = [{include = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
test = "src.data.spectra_loader:main"